server.port=8080
spring.thymeleaf.cache=false
logging.level.com.athan=INFO

# Build info ? injected by Maven at compile time
app.version=1.0.0
app.build.number=@build.number@

# Multipart upload settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=2KB
